-- 코드를 작성해주세요
SELECT DISTINCT(D.ID),EMAIL,FIRST_NAME,LAST_NAME
FROM DEVELOPERS D
LEFT JOIN SKILLCODES S
ON D.SKILL_CODE&S.CODE
WHERE S.NAME='Python'
OR S.NAME='C#'
ORDER BY ID ASC
;

# SELECT ID,EMAIL,FIRST_NAME,LAST_NAME
# FROM DEVELOPERS
# WHERE SUBSTRING(BIN(SKILL_CODE),LENGTH(BIN(SKILL_CODE))-8,1)=1
# OR SUBSTRING(BIN(SKILL_CODE),LENGTH(BIN(SKILL_CODE))-10,1)=1
# ORDER BY ID ASC
# ;