-- 코드를 입력하세요
-- 1. BOOK (테이블) : 도서 정보
-- BOOK_ID (도서 ID), CATEGORY (카테고리), AUTHOR_ID (저자 ID), PRICE (판매가), PUBLISHED_DATE (출판일)

-- 2. BOOK_SALES (테이블) : 판매 정보
-- BOOK_ID (도서 ID), SALES_DATE (판매일), SALES (판매량)

-- 문제
# 2022-01의 CATEGORY 별 SALES를 합산하고 CATEGORY, TOTAL_SALES 리스트를 출력
# CATEGORY 기준으로 오름차순 정렬

SELECT B.CATEGORY,SUM(SALES) AS TOTAL_SALES
FROM BOOK B
LEFT JOIN BOOK_SALES S
ON B.BOOK_ID = S.BOOK_ID
WHERE S.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY CATEGORY
ORDER BY CATEGORY ASC
;