-- 코드를 입력하세요
-- 1. BOOK (테이블) : 도서 정보
-- BOOK_ID (도서 ID), CATEGORY (카테고리), AUTHOR_ID (저자 ID), PRICE (판매가)
-- , PUBLISHED_DATE (출판일)

-- 2. AUTHOR (테이블) : 저자 정보
-- AUTHOR_ID (저자 ID), AUTHOR_NAME (저자명)

-- 문제
# '경제' CATEGORY에 속하는 도서들의 BOOK_ID, AUTHOR_NAME, PUBLISHED_DATE 리스트를 출력
# PUBLISHED_DATE을 기준으로 오름차순 정렬

SELECT BOOK_ID, AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE, "%Y-%m-%d") AS PUBLISHED_DATE
FROM BOOK B
LEFT JOIN AUTHOR A
ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE CATEGORY='경제'
ORDER BY PUBLISHED_DATE ASC
;